/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chris_crypt_utils_Native */

#ifndef _Included_com_chris_crypt_utils_Native
#define _Included_com_chris_crypt_utils_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chris_crypt_utils_Native
 * Method:    dbz
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_chris_crypt_utils_Native_dbz
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_chris_crypt_utils_Native
 * Method:    db
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chris_crypt_utils_Native_db
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_chris_crypt_utils_Native
 * Method:    uuu
 * Signature: (Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chris_crypt_utils_Native_uuu
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_chris_crypt_utils_Native
 * Method:    uu
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_chris_crypt_utils_Native_uu
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
